import type {Metadata} from 'next';
import '@/src/styles/globals.css';
import Link from 'next/link';
import {Providers} from './providers';
export const metadata: Metadata = {
  title: 'Holiday Scraper Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-full">
        <Providers>
          <nav className="bg-gray-800 p-4">
            <div className="container mx-auto flex justify-between items-center">
              <div className="text-white text-lg font-bold">Holiday scraper</div>
              <div className="flex space-x-4">
                <Link href="/" className="text-white hover:underline">
                  Scraper
                </Link>
                <Link href="/history" className="text-white hover:underline">
                  History
                </Link>
              </div>
            </div>
          </nav>
          <main className="container mx-auto mt-10" style={{minHeight: 'calc(100vh - 80px)'}}>
            {children}
          </main>
          <footer className="bg-gray-800 p-4 text-white text-center">Footer content here</footer>
        </Providers>
      </body>
    </html>
  );
}
